-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "schedule-whiz-v1"."Employees"
(
    employee_id serial NOT NULL,
    names character varying(50) NOT NULL,
    first_surname character varying(50) NOT NULL,
    second_surname character varying(50) NOT NULL,
    schedule serial,
    team serial NOT NULL,
    managed_team serial,
    CONSTRAINT "Employees_pkey" PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS "schedule-whiz-v1"."Schedules"
(
    schedule_id serial NOT NULL,
    name character varying(50) NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    max_employees integer,
    current_employees integer,
    PRIMARY KEY (schedule_id)
);

CREATE TABLE IF NOT EXISTS "schedule-whiz-v1"."Teams"
(
    team_id serial NOT NULL,
    name character varying(100),
    PRIMARY KEY (team_id)
);

CREATE TABLE IF NOT EXISTS "schedule-whiz-v1"."Records"
(
    record_id serial NOT NULL,
    employee serial NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    PRIMARY KEY (record_id)
);

CREATE TABLE IF NOT EXISTS "schedule-whiz-v1"."Issues"
(
    issue_id serial NOT NULL,
    record serial NOT NULL,
    issue_status serial NOT NULL,
    delay time without time zone,
    description character varying(280),
    PRIMARY KEY (issue_id)
);

CREATE TABLE IF NOT EXISTS public."Issue_statuses"
(
    issue_status_id serial NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (issue_status_id)
);

ALTER TABLE IF EXISTS "schedule-whiz-v1"."Employees"
    ADD FOREIGN KEY (team)
    REFERENCES "schedule-whiz-v1"."Teams" (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "schedule-whiz-v1"."Employees"
    ADD FOREIGN KEY (schedule)
    REFERENCES "schedule-whiz-v1"."Schedules" (schedule_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "schedule-whiz-v1"."Employees"
    ADD FOREIGN KEY (managed_team)
    REFERENCES "schedule-whiz-v1"."Teams" (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "schedule-whiz-v1"."Records"
    ADD FOREIGN KEY (employee)
    REFERENCES "schedule-whiz-v1"."Employees" (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "schedule-whiz-v1"."Issues"
    ADD FOREIGN KEY (record)
    REFERENCES "schedule-whiz-v1"."Records" (record_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "schedule-whiz-v1"."Issues"
    ADD FOREIGN KEY (issue_status)
    REFERENCES public."Issue_statuses" (issue_status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
